/*
 * LibreriaTPM.c
 *
 *  Created on: Dec 5, 2015
 *      Author: user
 */

#include<LibreriaTPM.h>
void configurarTPM(void){
	//CONFIGURACIÓN TPM PARA MOTORES 
	
	TPM2SC_CPWMS = 1; //LOS CANALES DE TPM2 se configuran como PWM alineado en el centro
	TPM2MOD =0xff;//VALOR DE LA MITAD DEL PERIODO DE LA SEÑAL PWM %%DETERMINAR%%
	//PARA EL CANAL 0 DEL TPM2 (MOTOR1)
	TPM2C0SC_ELS0A=0;//
	TPM2C0SC_ELS0B=1;//FLANCO DE BAJADA CUANDO EL CONTADOR EN SUBIDA LLEGA A LA MITAD DEL VALOR DEL CANAL
	TPM2C0V=0x70;//VALOR DE LA MITAD DEL TIEMPO EN ALTO DE LA SEÑAL PWM
	
	//PARA EL CANAL 1 DEL TPM2 (MOTOR2)
	TPM2C1SC_ELS1A=0;//
	TPM2C1SC_ELS1B=1;//FLANCO DE BAJADA CUANDO EL CONTADOR EN SUBIDA LLEGA A LA MITAD DEL VALOR DEL CANAL
	TPM2C1V=0xf0;//VALOR DE LA MITAD DEL TIEMPO EN ALTO DE LA SEÑAL PWM
	
	//CONFIGURACION TPM ENCODERS COMO CAPTURA DE ENTRADA 
	////ENCODER1
	//PARA EL CANAL 0 DE TPM1
    TPM1C0SC_MS0A  = 0;                
    TPM1C0SC_MS0B =0;  //CONFIGURACIÓN DEL CANAL COMO CAPTURA DE ENTRADA 
    TPM1C0SC_ELS0A=1;//
    TPM1C0SC_ELS0B=0;//CONFIGURO LA CAPTURA POR FLANCO DE SUBIDA EN EL PIN 
    TPM1C0SC_CH0IE=1;//HABILITO INTERRUPCIÓN POR EL FLANCO DE SUBIDA 
	//PARA EL CANAL 1 DE TPM1
    TPM1C1SC_MS1A = 0;                
    TPM1C1SC_MS1B =0;  //CONFIGURACIÓN DEL CANAL COMO CAPTURA DE ENTRADA 
    TPM1C1SC_ELS1A=1;//
    TPM1C1SC_ELS1B=0;//CONFIGURO LA CAPTURA POR FLANCO DE SUBIDA EN EL PIN 
    TPM1C1SC_CH1IE=1;//HABILITO INTERRUPCIÓN POR EL FLANCO DE SUBIDA 
    ////ENCODER2
	//PARA EL CANAL 2 DE TPM1
    TPM1C2SC_MS2A = 0;                
    TPM1C2SC_MS2B =0;  //CONFIGURACIÓN DEL CANAL COMO CAPTURA DE ENTRADA 
    TPM1C2SC_ELS2A=1;//
    TPM1C2SC_ELS2B=0;//CONFIGURO LA CAPTURA POR FLANCO DE SUBIDA EN EL PIN 
    TPM1C2SC_CH2IE=1;//HABILITO INTERRUPCIÓN POR EL FLANCO DE SUBIDA 
    //PARA EL CANAL 3 DE TPM1
     TPM1C3SC_MS3A = 0;                
     TPM1C3SC_MS3B =0;  //CONFIGURACIÓN DEL CANAL COMO CAPTURA DE ENTRADA 
     TPM1C3SC_ELS3A=1;//
     TPM1C3SC_ELS3B=0;//CONFIGURO LA CAPTURA POR FLANCO DE SUBIDA EN EL PIN 
     TPM1C3SC_CH3IE=1;//HABILITO INTERRUPCIÓN POR EL FLANCO DE SUBIDA 
        
    
}
